# Generated by staticimports; do not edit by hand.
# ======================================================================

fixed <- function(pattern, ignore_case = FALSE) {
	if (!isTRUE(ignore_case)) {
		return(structure(
			pattern, class = c("stringr_fixed", "stringr_pattern", "character")
		))
	}

	if (!is.null(names(pattern))) {
		names(pattern) <- paste0("(?i)", names(pattern))
	} else {
		pattern <- paste0("(?i)", pattern)
	}

	structure(pattern, class = c("stringr_regex", "stringr_pattern", "character"))
}

regex <- function(
	pattern,
	ignore_case = FALSE,
	multiline = FALSE,
	comments = FALSE,
	dotall = FALSE
) {
	options <- paste(
		if (isTRUE(ignore_case)) "i",
		if (isTRUE(multiline)) "m",
		if (isTRUE(dotall)) "s",
		if (isTRUE(comments)) "x",
		sep = ""
	)

	if (nzchar(options)) {
		if (!is.null(names(pattern))) {
			names(pattern) <- paste0("(?", options, ")", names(pattern))
		} else {
			pattern <- paste0("(?", options, ")", pattern)
		}
	}

	structure(pattern, class = c("stringr_regex", "stringr_pattern", "character"))
}
