# Generated by staticimports; do not edit by hand.
# ======================================================================

str_match <- function(string, pattern) {
	if (length(string) == 0 || length(pattern) == 0) return(matrix(character(0)))

	is_fixed <- inherits(pattern, "stringr_fixed")

	matches <- mapply(
		function(string, pattern) {
			if (is.na(string) || is.na(pattern)) return(NA_character_)

			regmatches(
				x = string,
				m = regexec(
					pattern = pattern, text = string, perl = !is_fixed, fixed = is_fixed
				)
			)
		},
		string, pattern, USE.NAMES = FALSE
	)

	length <- max(lengths(matches))
	matches <- lapply(matches, `[`, seq_len(length))

	result <- do.call(rbind, matches)
	result[result == ""] <- NA_character_
	result
}
