# Generated by staticimports; do not edit by hand.
# ======================================================================

str_squish <- function(string) {
	string <- sub("^\\s+", "", string, perl = TRUE)
	string <- sub("\\s+$", "", string, perl = TRUE)
	gsub("\\s+", " ", string, perl = TRUE)
}

str_trim <- function(string, side = c("both", "left", "right")) {
	side <- match.arg(side)
	if (side != "right") string <- sub("^\\s+", "", string, perl = TRUE)
	if (side != "left") string <- sub("\\s+$", "", string, perl = TRUE)
	string
}
