# Generated by staticimports; do not edit by hand.
# ======================================================================

str_count <- function(string, pattern = "") {
	is_fixed <- inherits(pattern, "stringr_fixed")

	count <- mapply(
		function(string, pattern) {
			match <- unlist(
				gregexpr(pattern, text = string, perl = !is_fixed, fixed = is_fixed)
			)
			length(match[match > 0])
		},
		string, pattern, SIMPLIFY = "vector", USE.NAMES = FALSE
	)

	mode(count) <- "integer"
	count
}
