# Generated by staticimports; do not edit by hand.
# ======================================================================

str_length <- function(string) {
	nchar(as.character(string), type = "chars", keepNA = TRUE)
}

str_width <- function(string) {
	nchar(as.character(string), type = "width", keepNA = TRUE)
}
