# Generated by staticimports; do not edit by hand.
# ======================================================================

str_remove <- function(string, pattern) {
	is_fixed <- inherits(pattern, "stringr_fixed")

	string <- Vectorize(sub, c("pattern", "x"), USE.NAMES = FALSE)(
		pattern, replacement = "", x = string, perl = !is_fixed, fixed = is_fixed
	)

	mode(string) <- "character"
	string
}

str_remove_all <- function(string, pattern) {
	is_fixed <- inherits(pattern, "stringr_fixed")

	string <- Vectorize(gsub, c("pattern", "x"), USE.NAMES = FALSE)(
		pattern, replacement = "", x = string, perl = !is_fixed, fixed = is_fixed
	)

	mode(string) <- "character"
	string
}
